### PR TITLE
Feat(Data): Add Dango Defender

### PR DESCRIPTION
**Pull request by WetU**

### CODE REVIEW

**Review by Haato3o — CHANGES_REQUESTED** [review]
Same issue as the other PR, the icon is too huge.

**Comment by WetU** [comment]
I used this tool: https://github.com/BerndK/SvgToXaml
Image conversion is my first try.
Oh, Dango Defender icon is not visible at this commit.
Please help to create icon

**Comment by Haato3o** [comment]
Yea, I use that tool too to convert from SVG to Xaml, but the issue is that it really depends on how the SVG was made. I usually make the icons by hand myself if they're not complex, but if it's a complex icon then I use some png to svg rasterizer, tweaking the settings to not generate a svg with a huge amount of shapes

**Comment by WetU** [comment]
I changed color from Divine Protection icon.
Dango Defender buff icon has same shape with Divine Protection. only diffence is color.

**Review by Haato3o — APPROVED** [review]

**Review by Haato3o — APPROVED** [review]

**Pull request merged**
